name: Copy Code to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare SSH key
      run: |
        mkdir -p tmp_ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > tmp_ssh/private_key
        chmod 600 tmp_ssh/private_key

    - name: Copy files to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i tmp_ssh/private_key" --exclude=tmp_ssh . $USER@$HOST:/home/ubuntu/test

    - name: Cleanup SSH key
      run: |
        rm -rf tmp_ssh
