name: Deploy to EC2 and Add .env File

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare SSH key
      run: |
        mkdir -p tmp_ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > tmp_ssh/private_key
        chmod 600 tmp_ssh/private_key

    - name: Copy files to EC2, change permissions, and add .env file
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        ENCODED_DOTENV: ${{ secrets.ENCODED_DOTENV }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i tmp_ssh/private_key" --exclude=tmp_ssh . $USER@$HOST:/home/ubuntu/test
        ssh -o StrictHostKeyChecking=no -i tmp_ssh/private_key $USER@$HOST << EOF
          sudo chown -R ubuntu:ubuntu /home/ubuntu/test
          echo "$ENCODED_DOTENV" | base64 -d | sudo tee /home/ubuntu/test/.env > /dev/null
          sudo chown ubuntu:ubuntu /home/ubuntu/test/.env
        EOF

    - name: Cleanup SSH key
      run: |
        rm -rf tmp_ssh
