name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -v -i private_key -o StrictHostKeyChecking=no $USER@$HOST 'pwd' << EOF
          # Commands to execute on your EC2 instance
          # For example, pulling the latest code and restarting the service
          cd /path/to/your/project
          git pull
          # restart your application/service if needed
        EOF
